kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: build # 定义流水线名称

steps: # 定义流水线执行步骤，这些步骤将顺序执行
  - name: build
    image: appleboy/drone-ssh # SSH工具镜像
    pull: if-not-exists
#    network_mode: host
    settings:
      host: 172.40.0.1 # 远程连接地址
      username: root # 远程连接账号
      password:
        from_secret: ssh_password # 从Secret中读取SSH密码
      port: 22 # 远程连接端口
      command_timeout: 5h # 远程执行命令超时时间
      script:
        - ./all.sh
#        - chmod
#        - cd /home/asialjim/.DroneImage/maven/build # 进入宿主机构建目录
#        - chmod +x run.sh # 更改为可执行脚本
#        - ./run.sh # 运行脚本打包应用镜像并运行

volumes: # 定义流水线挂载目录，用于共享数据
  - name: maven-cache
    host:
      path: /home/asialjim/.m2
  - name: ssh-cache
    host:
      path: /home/asialjim/.ssh
  - name: docker
    host:
      path: /var/run/docker.sock