kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: build # 定义流水线名称

steps: # 定义流水线执行步骤，这些步骤将顺序执行
  - name: build # 流水线名称
    image: asialjim/maven-with-gpg:latest
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: maven-cache
        path: /root/.m2 # 将maven下载依赖的目录挂载出来，防止重复下载
      - name: maven-settings
        path: /root/.m2/settings.xml
      - name: ssh-cache
        path: /root/.ssh
    commands: # 定义在Docker容器中执行的shell命令
      - sh all.sh

volumes: # 定义流水线挂载目录，用于共享数据
  - name: maven-cache
    host:
      path: /home/asialjim/.m2
  - name: ssh-cache
    host:
      path: /home/asialjim/.ssh
  - name: maven-settings
    host:
      path: /home/asialjim/.m2/settings.xml