kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: build # 定义流水线名称

steps: # 定义流水线执行步骤，这些步骤将顺序执行
  - name: install
    image: drone/drone-runner-docker:1 # SSH工具镜像
    volumes:
      - name: maven-cache
        path: /home/asialjim/.m2
      - name: ssh-cache
        path: /home/asialjim/.ssh
      - name: docker
        path: /var/run/docker.sock # 挂载宿主机的docker
    commands: # 定义在Docker容器中执行的shell命令
      - sh all.sh

volumes: # 定义流水线挂载目录，用于共享数据
  - name: maven-cache
    host:
      path: /home/asialjim/.m2
  - name: ssh-cache
    host:
      path: /home/asialjim/.ssh
  - name: docker
    host:
      path: /var/run/docker.sock