kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: build # 定义流水线名称

steps: # 定义流水线执行步骤，这些步骤将顺序执行
  - name: package # 流水线名称
    image: maven:3.8.6-openjdk-8 # 定义创建容器的Docker镜像
    pull: if-not-exists
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: maven-build
        path: /app/build # 将应用打包好的Jar和执行脚本挂载出来
    commands: # 定义在Docker容器中执行的shell命令
      - cp *.sh /app/build/

  - name: build
    image: appleboy/drone-ssh # SSH工具镜像
    pull: if-not-exists
    settings:
      tty: true
      host: 172.40.0.1 # 远程连接地址
      username: root # 远程连接账号
      password:
        from_secret: ssh_password # 从Secret中读取SSH密码
      port: 22 # 远程连接端口
      command_timeout: 5h # 远程执行命令超时时间
      script:
        - cd /home/asialjim/.app/docker/gitee/ci
        - pwd
        - ls -la
        - chmod +x *.sh # 更改为可执行脚本
        - ./all.sh


volumes: # 定义流水线挂载目录，用于共享数据
  - name: maven-cache
    host:
      path: /home/asialjim/.m2
  - name: ssh-cache
    host:
      path: /home/asialjim/.ssh
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: maven-build
    host:
      path: /home/asialjim/.app/docker/gitee/ci